import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar_JOR': {
          "believer": "بيليفر",
          "signUp": "التسجيل",
          "signIn": "تسجيل الدخول",
          "pleaseEmail": "الرجاء إدخال بريد إلكتروني صالح",
          "email": "البريد الإلكتروني",
          "createAcc": "إنشاء حساب",
          "pleasePassword": "الرجاء إدخال كلمة مرور تتكون من 8 أحرف على الأقل",
          "password": "كلمة المرور",
          "forgot": "هل نسيت كلمة المرور؟",
          "description": "الوصف",
          "name": "الاسم",
          "hi": "مرحبًا",
          "best": "الأكثر مبيعًا",
          "google": "جوجل",
          "apple": "آبل",
          "skip": "المتابعة كضيف",
          "pleaseName": "الرجاء إدخال اسمك",
          "agree": "موافق على",
          "term": "الشروط والأحكام",
          "invalidCredentials": "بيانات الولوج غير صحيحة",
          "email-already-in-use": "البريد الإلكتروني مستخدم بالفعل",
          "submit": "إرسال",
          "resetPassword": "إعادة تعيين كلمة المرور",
          "passwordSent":
              "لإعادة تعيين كلمة المرور، يرجى التحقق من صندوق البريد الوارد أو البريد العشوائي",
          "search": "بحث",
          "deliverTO": "توصيل إلى",
          "home": "الرئيسية",
          "profile": "الملف الشخصي",
          "cart": "السلة",
          "wishlist": "قائمة الرغبات",
          "category": "الفئة",
          "seeAll": "عرض الكل",
          "noProducts": "لا توجد منتجات متاحة",
          "noFavorites": "لا يوجد منتج مفضل حاليًا",
          "AED": "درهم إماراتي",
          "subtotal": "المجموع الفرعي",
          "items": "العناصر",
          "deliveryFee": "رسوم التوصيل",
          "pleaseFirst": "الرجاء تسجيل الدخول أولاً",
          "CHECKOUT": "الدفع",
          "emptyCart": "سلة التسوق فارغة",
          "orderPlaced": "تم وضع الطلب",
          "total": "الإجمالي",
          "pleaseAddress": "الرجاء إضافة عنوان أولاً",
          "placeOrder": "تأكيد الطلب",
          "shipping": "تفاصيل التوصيل",
          "addNew": "إضافة عنوان",
          "change": "تغيير",
          "noData": "لا توجد بيانات",
          "orderDetails": "تفاصيل الطلب",
          "upTo": "حتى",
          "orderList": "قائمة الطلبات",
          "expired": "انتهت صلاحية رمز الخصم",
          "noCode": "لا يوجد رمز",
          "havePromo": "هل لديك رمز ترويجي؟",
          "promo": "رمز ترويجي",
          "address": "العنوان",
          "newAddress": "عنوان جديد",
          "noAddress": "لا توجد عناوين محفوظة",
          "default": "الافتراضي",
          "homes": "المنزل",
          "work": "العمل",
          "favorites": "المفضلة",
          "label": "علامة العنوان",
          "pleaseAddressName": "الرجاء إدخال اسم العنوان",
          "pleaseYourAddress": "الرجاء إدخال عنوانك",
          "pleasephone": "الرجاء إدخال رقم هاتفك",
          "addressName": "اسم العنوان",
          "phone": "الهاتف",
          "categories": "الفئات",
          "orderNo": "رقم الطلب",
          "inProgress": "قيد التنفيذ",
          "cancel": "تم الإلغاء",
          "cancelx": "إلغاء",
          "complete": "اكتمل",
          "inDelivery": "قيد التوصيل",
          "discount": "خصم",
          "makeDefualt": "اجعله الافتراضي",
          "deleteAddress": "حذف العنوان",
          "orderNumber": "رقم الطلب",
          "orderT&D": "وقت وتاريخ الطلب",
          "noOrders": "لا توجد طلبات حتى الآن",
          "sureDelete": "هل أنت متأكد أنك تريد حذف حسابك؟",
          "remove": "إزالة",
          "status": "الحالة",
          "myOrders": "طلباتي",
          "manageAdd": "إدارة العناوين",
          "settings": "الإعدادات",
          "help": "مركز المساعدة",
          "contactUs": "اتصل بنا",
          "logOut": "تسجيل الخروج",
          "notifications": "الإشعارات",
          "noNotifications": "لا توجد إشعارات",
          "changeEmail": "تغيير البريد الإلكتروني",
          "changePass": "تغيير كلمة المرور",
          "changeLang": "تغيير اللغة",
          "delete": "حذف",
          "deleteAccount": "حذف حسابك",
          "reviewSent": "تم إرسال التقييم",
          "reviewOrder": "مراجعة الطلب",
          "message": "الرسالة",
          "veryGood": "جيد جداً",
          "noPayment": "لا توجد طرق دفع محفوظة",
          "paymentMethod": "طرق الدفع",
          "add": "إضافة",
          "filter": "تصفية",
          "price": "السعر",
          "stock": "في المخزن",
          "titleAr": "العنوان باللغة العربية",
          "titleEn": "العنوان باللغة الإنجليزية",
          "descriptionEn": "الوصف باللغة الإنجليزية",
          "descriptionAr": "الوصف باللغة العربية",
          "discountP": "نسبة الخصم",
          "max": "الحد الأقصى للخصم",
          "code": "كود الكوبون",
          "out": "انتهت الكمية",
          "addTo": "اضف للسلة",
          "update": "تحديث"
        },
        'en_US': {
          "believer": "Believer",
          "signUp": "Sign Up",
          "signIn": "Sign In",
          "pleaseEmail": "Please enter valid Email",
          "email": "Email",
          "createAcc": "   Create account",
          "pleasePassword": "Please enter password at least 8 characters",
          "password": "Password",
          "forgot": "Forgot password?",
          "description": "Description",
          "name": "Name",
          "hi": "Hi",
          "best": "  Best seller",
          "google": "Google",
          "apple": "Apple",
          "skip": "Continue as Guest",
          "pleaseName": "Please enter your name",
          "agree": "Agree with",
          "term": "Terms & Conditions",
          "invalidCredentials": "Invalid credentials",
          "email-already-in-use": "Email already used",
          "submit": "Submit",
          "resetPassword": "Reset your password",
          "passwordSent":
              "To reset your password check your email inbox or spam",
          "search": "Search",
          "deliverTO": "Deliver to",
          "home": "Home",
          "profile": "Profile",
          "cart": "Cart",
          "wishlist": "Wishlist",
          "category": "Category",
          "seeAll": "See All",
          "noProducts": "No products available",
          "noFavorites": "No favorite products yet",
          "AED": "AED",
          "subtotal": "Subtotal",
          "items": "items",
          "deliveryFee": "Delivery Fee",
          "pleaseFirst": "Please sign in first",
          "CHECKOUT": "Checkout",
          "emptyCart": "Your cart is empty",
          "orderPlaced": "Order placed",
          "total": "Total",
          "pleaseAddress": "Please add an address first",
          "placeOrder": "Place order",
          "shipping": "Delivey details",
          "addNew": " Add address",
          "change": "Change",
          "noData": "No data found",
          "orderDetails": "Order details",
          "upTo": " up to",
          "orderList": "Order list",
          "expired": "Promo code expired",
          "noCode": " No code found",
          "havePromo": " Do you have promo code?",
          "promo": "Promo code",
          "address": "Address",
          "newAddress": "New Address",
          "noAddress": "No saved address",
          "default": "Default",
          "homes": "Home",
          "work": "Work",
          "favorites": "Favorites",
          "label": " Address label",
          "pleaseAddressName": "Please enter address name",
          "pleaseYourAddress": "Please enter your address",
          "pleasephone": "Please enter your phone number",
          "addressName": "Address name",
          "phone": "Phone",
          "categories": "Categories",
          "orderNo": "Order No",
          "inProgress": "In progress",
          "cancel": "canceled",
          "cancelx": "cancel",
          "complete": "completed",
          "inDelivery": "In delivery",
          "discount": "Discount",
          "makeDefualt": "Make it default",
          "deleteAddress": "Delete Address",
          "orderNumber": "Order Number",
          "orderT&D": "Order time & date",
          "noOrders": "No orders yet",
          "sureDelete": "Are you sure you want to delete your account?",
          "remove": "Remove",
          "status": "Status",
          "myOrders": "My orders",
          "manageAdd": "Manage Address",
          "settings": "Settings",
          "help": "Help Center",
          "contactUs": "Contact US",
          "logOut": "Log Out",
          "notifications": "Notifications",
          "noNotifications": "No notifications there",
          "changeEmail": "Change Email",
          "changePass": "Change Password",
          "changeLang": "Change language",
          "delete": " Delete",
          "deleteAccount": " Delete your Account",
          "reviewSent": "Review sent",
          "reviewOrder": "Review order",
          "message": "Message",
          "veryGood": "Very good",
          "noPayment": "No saved payment methods",
          "paymentMethod": "Payment methods",
          "add": "Add",
          "price": "Price",
          "stock": "In stock",
          "titleAr": "Title in Arabic",
          "titleEn": "Title in English",
          "descriptionEn": "Description in English",
          "descriptionAr": "Description in Arabic",
          "discountP": "Discount percent",
          "max": "Max dicount",
          "code": "Coupon code",
          "out": "Out of stock",
          "addTo": "Add to cart",
          "filter": "Filter",
          "update": "Update"
        }
      };
}
