name: believer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  lottie: ^2.7.0
  syncfusion_flutter_charts: ^23.2.4
  share_plus: ^6.3.4
  url_launcher: ^6.2.1
  fluttertoast: ^8.2.4
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_storage: ^11.4.1
  firebase_dynamic_links: ^5.4.3
  firebase_messaging: ^14.7.3
  cloud_firestore: ^4.12.2
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  icons_plus: ^4.0.0
  carousel_slider: ^4.2.1
  flutter_stripe: ^9.5.0+1
  hl_image_picker: ^1.2.8
  ticket_widget: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  flutter_credit_card: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
    - assets/lotties/
